apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: imjarois/fib_api
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: RABBIT_HOST
              value: workqueue-cluster-ip-service
            - name: RABBIT_PORT
              value: '5672'
            - name: RABBIT_USER
              value: guest
            - name: RABBIT_PASSWORD
              value: guest
            - name: PGHOST
              value: db-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATBASE
              value: postgres
            - name: PGUSER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom: # this will reference the PGPASSWORD key from the pgpassword Secret Object created in the cluster
                secretKeyRef:
                  name: postgres-password
                  key: POSTGRES_PASSWORD
