apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
    version: v1
spec:
  replicas: 4
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: imjarois/fib_worker
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: RABBIT_HOST
              value: workqueue-cluster-ip-service
            - name: RABBIT_PORT
              value: '5672'
            - name: RABBIT_USER
              value: guest
            - name: RABBIT_PASSWORD
              value: guest
